openapi: 3.0.0
info:
  title: Contact List API
  version: 1.0.0
paths:
  /contacts:
    get:
      summary: Get list of contacts
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search query for name, phone, or bio
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      pageSize:
                        type: integer
                      totalPages:
                        type: integer
                      hasMore:
                        type: boolean
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phone
              properties:
                name:
                  type: string
                phone:
                  type: string
                bio:
                  type: string
                avatar:
                  type: string
                  description: Base64 encoded image data
      responses:
        '201':
          description: Contact created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    put:
      summary: Update an existing contact
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                bio:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Contact updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    delete:
      summary: Delete a contact
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact deleted
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        bio:
          type: string
        avatar:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ContactInput:
      type: object
      required:
        - name
        - phone
      properties:
        name:
          type: string
        phone:
          type: string
        bio:
          type: string
        avatar:
          type: string
